### ISSUE TITLE
websocket 请求应该只返回更新的数据

### ISSUE THREAD

**Issue by AlexGuo1998** [maborosh/BandoriStation#3]
看了一下目前的情况，目前 WebSocket 请求是每半秒钟返回一次所有的数据，即使没有更新也会返回，这样会不会让服务器压力过大，或者浪费流量？

个人建议是 WebSocket 连接完毕后，除了第一次推下全部消息，以后每次都只推更新的消息，客户端做缓存处理；如果没有更新就不要推送了，避免消息过多。如果长时间没有消息，可以发一个心跳包保持连接活跃（或者让客户端主动发心跳包，更好）。

**Comment by maborosh** [comment]
感谢提供建议，后面的更新会考虑这个部分。目前是每次返回2分钟内的所有数据，如果两分钟内没有数据服务端是不会发送数据的。这种可能会造成浪费流量，但是服务端其实并没有什么压力。
